# introduction to numpy

In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.20.3


In [4]:
# creating 0,1 and 2 dimensional array

#0
zero=np.array(12.3,dtype='i')
print(zero)

#1
one=np.array([1,2,3])
print("---------")
print(one)

#2

two=np.array([[1,2,3,4],[5,6,7,8]])
print("---------")
print(two)

12
---------
[1 2 3]
---------
[[1 2 3 4]
 [5 6 7 8]]


In [5]:
#accessing array
#two access the 3rd element of second row that is seven 
print(two[1,2])

7


In [6]:
print(two.ndim)

2


In [15]:
#converting a array into x dimension

x=np.array([1,2,3,45,6],ndmin=0)
print(x)

[ 1  2  3 45  6]


In [14]:
x=np.array([1,2,3,4],ndmin=-1)
print(x)

[1 2 3 4]


In [17]:
#slicing an array

x=np.array([[1,2,3],[3,4,5],[5,6,7]])

#this is a 3*3 matrix
#to access last two columns

print(x[:,1:])

[[2 3]
 [4 5]
 [6 7]]


In [19]:
#to access last two rows
print(x[1: , :])

[[3 4 5]
 [5 6 7]]


In [20]:
#to access middle columns

print(x[:,1])

[2 4 6]


In [21]:
# we can also jmp by taking some steps

#for eg
x=np.array([1,2,3,4,5,6,7,8,9])

print(x[1::2])

#notw , here we went from 2 index to end by taking two steps at a time 

[2 4 6 8]


# Numpy datatypes

In [23]:
a=np.array([1,4,6,4,76,4,7])

print(a.dtype)

int32


In [26]:
x=a.astype("f")
print(x.dtype)

float32


In [27]:
#copying array
x=a.copy()
x[0]=23
print(x)
print(a)

[23  4  6  4 76  4  7]
[ 1  4  6  4 76  4  7]


In [28]:
# view function

x=a.view()
x[0]=23
print(x)
print(a)

'''note the difference between this cells output
and the last cells''' 

[23  4  6  4 76  4  7]
[23  4  6  4 76  4  7]


In [33]:
#getting to know the shape of the array

b=np.array([1,[[1,2,3]],[[4,5,6]],7])
print(b.shape)
print("-----------")
print(b)

(4,)
-----------
[1 list([[1, 2, 3]]) list([[4, 5, 6]]) 7]


C:\Users\JAYACH~1\AppData\Local\Temp/ipykernel_17972/3126798860.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  b=np.array([1,[[1,2,3]],[[4,5,6]],7])


In [34]:
b[1]=2
b[2]=4
print(b)
print(b.shape)

[1 2 4 7]
(4,)


In [37]:
#reshaping array

b=np.array([[1,2,3],[4,5,6]])
print(b.shape)
b=b.reshape(-1)
print(b.shape)
b=b.reshape((6,1))
print(b.shape)

(2, 3)
(6,)
(6, 1)


In [39]:
# ndenumerate function

for idx,i in np.ndenumerate(b):
    
    print(idx,i)
    
#here idx would be just like the location(coordinates of i) of i

(0, 0) 1
(1, 0) 2
(2, 0) 3
(3, 0) 4
(4, 0) 5
(5, 0) 6


In [45]:
# joining arrays

arr1=np.array([1,2,3])
arr2=np.array([7,8,9])
arr3=np.array([4,5,6])

arr4=np.concatenate((arr1,arr2),axis=0)
print(arr4)

arr4=arr4.reshape((2,3))
arr3=arr3.reshape((1,3))

arr5=np.concatenate((arr3,arr4),axis=0)

print(arr5)

[1 2 3 7 8 9]
[[4 5 6]
 [1 2 3]
 [7 8 9]]


# searching in arrays

In [48]:
# using where method which returns the index positions

a=np.array([1,2,2,3,45,67,67,67,88,8])
b=np.where(a==67)
print(b)
print(type(b))
print(len(b))

(array([5, 6, 7], dtype=int64),)
<class 'tuple'>
1


In [50]:
c=np.where(a>8)
print(c)

(array([4, 5, 6, 7, 8], dtype=int64),)


# Random number generation in numpy

In [53]:
from numpy import random

In [54]:
x=random.randint(12,35,(2,3))

print(x)
print(x.shape)
print(x.dtype)

[[22 19 29]
 [27 23 31]]
(2, 3)
int32


In [55]:
#to generate ramdom numbers between zero and 1

x=random.rand(4,4)
print(x)

[[0.92995884 0.5982805  0.90188292 0.54712841]
 [0.30058024 0.62654892 0.26657353 0.61124291]
 [0.46289365 0.42743644 0.62766847 0.80593757]
 [0.70486384 0.09070294 0.12466467 0.22112533]]


# Mathematical function

In [56]:
c=np.array([1,2,3])
d=np.array([2,3,4])
multiplied=np.multiply(c,d)
added=np.add(c,d)
subtract=np.subtract(c,d)
devided=np.divide(c,d)


In [57]:
print(multiplied)
print(added)
print(subtract)
print(devided)


[ 2  6 12]
[3 5 7]
[-1 -1 -1]
[0.5        0.66666667 0.75      ]


In [58]:
# we can also perform matrix multiplication

x=random.randint(1,3,(1,3))
y=random.randint(1,3,(3,1))
z=np.dot(x,y)
print(z)
print(z.shape)

[[6]]
(1, 1)


# there are so many statstical function which we can use

In [59]:
a=np.array([1,2,2,3,4,23,54,66,77,66,78,12])

In [66]:
print(a.mean())
print(np.median(a))
print(np.max(a))
print(np.var(a))
print(np.min(a))
print(np.std(a))

32.333333333333336
17.5
78
983.5555555555557
1
31.361689296904203


In [67]:
# there are many more things you can do using numpy


# Keep exploring!!